language: python

python:
  - "3.6"

before_install:
  - sudo apt-get install portaudio19-dev
  - sudo apt-get install python-pyaudio

install:
  - pip install -r requirements.txt

script:
  - coverage run --source=ksoundcaptcha -m py.test

after_success:
  - coveralls