language: python

python:
  - "3.6"

before_install:
  - sudo apt-get install portaudio19-dev
  - sudo apt-get install python-pyaudio

install:
  - pip install -r requirements.txt

script:
  - flask run
  - sleep 10
  - python setup.py test